### PR TITLE
adding files for installing 5.x solr

### PR DESCRIPTION
**Pull request by soletan**
Pull request is providing separate XML configuration files for installing Solr 5.x releases. In combination with separate pull request on opus4/installation revised installer is preferring files containing specific version of solr service to be installed over generic ones.

> On installing Solr 5.2.1 this files in descending precedence are preferred over the generic one (which is schema.xml):
1. schema-5.2.1.xml
2. schema-5.2.xml
3. schema-5.xml.
> Same applies to solrconfig.xml

### CODE REVIEW

**Comment by j3nsch** [comment]
What is empty core.properties file used for?

**Comment by j3nsch** [comment]
schema-5.2.xml and schema-5.2.1.xml?

**Comment by j3nsch** [comment]
Do I understand correctly that the configuration files need to be placed in ${BASEDIR}/solrconfig of the OPUS instance (like with the Tarball until now)? I am just checking that I didn't overlook anything.

**Comment by j3nsch** [comment]
Thanks for the 5.x configuration.

**Comment by soletan** [comment]
empty core.properties: This is particularly required by Solr to find configured cores in multi-core setup. It might contain actual properties. In case of an empty core.properties file defaults are applied, partially relying on auto-detected values.

schema-x.y.z.xml ... the example is talking about precedence and thus it is theoretical, yes. It might help in setting up solr differently depending on whether it is 5.x or 4.x or 4.4 or 4.9.1 vs. 4.10.4 ...

configuration: I tried adopting the way solr was set up before. However, Solr has changed quite much with 5.x release and did so in more recent 4.x releases as well. Thus 

* BASEDIR/solr is still the path containing all solr files, 
* BASEDIR/solr/opus4 is still containing the HOME of current solr instance, 
* BASEDIR/solr/opus4/solr is a core of that instance

schema.xml and solrconfig.xml are expected in conf folder of every configured core, so they are to be placed in BASEDIR/solr/opus4/solr/conf/ ...

**Comment by j3nsch** [comment]
Thanks for the explanation. As I understand it we don't have to add cores to `solr.xml` anymore but can create subfolders with `core.properties` and the configuration files to add more cores. I like that. Makes it easier. I guess for hosting purposes it is possible to specify the configuration files in the properties and thus share the files across cores. Should work. I will try it and add it to the documentation. Hosting setups are more manuall anyway.

**Pull request merged**
